### ISSUE TITLE
Разработать библиотеку menu.hpp

### ISSUE THREAD

**Issue by UndergroundEvo** [trpo2023/cw-ip-111_hundred_matches#2]
Разработать библиотеку с методами для игрового меню:
- [x] Первоначальное меню;
- [x] Меню выбора режима игры (PvE, PvP, EvE);
- [x] Правила игры ([Информация из ТЗ по функциональности](https://github.com/trpo2023/cw-ip-111_hundred_matches/blob/main/docs/tech-requirement.md));
- [x] Авторы
- [x] Выход из игры

**Comment by AnFoxyn** [comment]
Реализовано, коммит запушен:
- **c4307fa** *Реализация библиотеки menu.h и зачатки game.h*
