### ISSUE TITLE
Разработать режим игры "Игрок против Компьютера"

### ISSUE THREAD

**Issue by UndergroundEvo** [trpo2023/cw-ip-111_hundred_matches#3]
Разработать логику игры для PvE режима в game.cpp

**Comment by AnFoxyn** [comment]
Предлагаю сначала сделать всю логику в библиотеках:
- [player.h](https://github.com/trpo2023/cw-ip-111_hundred_matches/issues/7)
- [computer.h](https://github.com/trpo2023/cw-ip-111_hundred_matches/issues/8)
- [matches.h](https://github.com/trpo2023/cw-ip-111_hundred_matches/issues/9)

Чтобы уже потом собрать сами режимы игры
